added CountlyConfig and initWithConfig
Countly/countly-sdk-rnb-example pull request #12
Opened 2023-02-13 20:39 UTC by peterbrown0

2023-02-20 11:49 UTC, ArtursKadikis requested changes
there is only 1 init. the approach that uses the config object.

2023-04-11 08:56 UTC, ArtursKadikis requested changes

2023-04-11 08:56 UTC, ArtursKadikis commented on CountlyRNExample/App.tsx
> +const COUNTLY_APP_KEY = '58594c9a3f461ebc000761a68c2146659ef75ea0';
let's not have realy keys here

2023-04-11 09:59 UTC, peterbrown0 commented on CountlyRNExample/App.tsx
> +const COUNTLY_APP_KEY = '58594c9a3f461ebc000761a68c2146659ef75ea0';
removed

2023-04-25 13:23 UTC, ArtursKadikis approved these changes

2023-04-25 13:23 UTC, merged